### ISSUE TITLE
Wrong zh_TW translation of "programmer"

### ISSUE THREAD

**Issue by 910JQK** [Rocaloid/rocaloid-website-experimental#1]
in locales/zh_TW.yml #26
「程序員」→「程式員」

**Comment by m13253** [comment]
非常感谢！

**Comment by m13253** [comment]
非常感謝。
新的文案正在staging，預計今天晚上可以上線。

**Comment by m13253** [comment]
Fixed in 5af67e9c7e1408747aac3b1e5f2e55e7b0dfc149

**Comment by m13253** [comment]
根據 Microsoft 術語集修訂「programmer」的翻譯為「程式設計師」。
